name: Build
on:
    workflow_call:
      inputs:
        workspace:
            description: 'The Terraform workspace'
            required: true
            type: string

permissions:
  contents: 'read'
  packages: 'write'


jobs:
    build_project:
        runs-on: ubuntu-latest
        outputs:
          image_tag: ${{ env.image_tag }}
        steps:
            - name: 'Checkout Code'
              uses: actions/checkout@v4

            - name: 'Current workspace for build'
              run: |
                echo "Current workspace for build: ${{ inputs.workspace }}"
                
            - name: Upload Artifact
              id: upload-artifact
              uses: actions/upload-artifact@v2
              with:
                name: my-artifact
                path: ./main_project

            - name: Tag Docker image
              id: tag_image
              run: |
                IMAGE_TAG=${{ github.sha }}
                echo "image_tag=${IMAGE_TAG}" >> $GITHUB_ENV
                
            - name: 'Docker image tag'
              run: |
                echo "Current tag for deploy is: ${{ env.image_tag }}"
    
    
    
    build_functions:
      runs-on: ubuntu-latest
      steps:
        - name: 'Checkout Code'
          uses: actions/checkout@v4

        - name: 'Current workspace for building functions'
          run: |
            echo "Current workspace for build: ${{ inputs.workspace }}"
    