name: terraform

on:
  push:
    branches: ["main"]

permissions:
  contents: 'read'
  packages: 'write'

env:
  twitposter_image: 'ghcr.io/wallyrion/twitposter:latest'

jobs:
  deploy_dev:
    name: Deploy to Dev
    uses: ./.github/workflows/shared.yml
    with:
      environment: dev
      workspace: dev
    secrets: inherit
  
  deploy_prod:
    needs: deploy_dev
    name: Deploy to prod
    uses: ./.github/workflows/shared.yml
    with:
        environment: prod
        workspace: prod
    secrets: inherit
