name: terraform

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: 'read'
  packages: 'write'

env:
  twitposter_image: 'ghcr.io/wallyrion/twitposter:latest'

jobs:
  deploy_dev:
    name: 'Terraform Deploy dev'
    runs-on: ubuntu-latest
    environment: dev
  
    steps:
      - name: 'Checkout GitHub Actions'
        uses: actions/checkout@v4


  deploy_prod:
    name: 'Terraform Deploy prod'
    runs-on: ubuntu-latest
    environment: prod
    needs: deploy_dev
    if: ${{ github.event.inputs.approve == 'true' }}
  
    steps:
      - name: 'Checkout GitHub Actions'
        uses: actions/checkout@v4