name: Deploy environment

on:
    workflow_call:
      inputs:
        environment:
          description: 'The environment to deploy to'
          required: true
          type: string
        workspace:
            description: 'The Terraform workspace'
            required: true
            type: string


jobs:
    infra:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout Code'
              uses: actions/checkout@v4

            - name: 'Print Current Workspace'
              run: |
                echo "Current Workspace: ${{ inputs.workspace }}"


    build_project:
        needs: infra
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout Code'
              uses: actions/checkout@v4

            - name: 'Current workspace for build'
              run: |
                echo "Current workspace for build: ${{ inputs.workspace }}"

    deploy_project:
        needs: build_project
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout Code'
              uses: actions/checkout@v4

            - name: 'Current workspace for deploy'
              run: |
                echo "Current workspace for deploy: ${{ inputs.workspace }}"


    