name: Deploy environment

on:
    workflow_call:
      inputs:
        environment:
          description: 'The environment to deploy to'
          required: true
          type: string
        workspace:
            description: 'The Terraform workspace'
            required: true
            type: string

permissions:
  contents: 'read'
  packages: 'write'


jobs:
    infra:
      environment: ${{ inputs.workspace }}
      runs-on: ubuntu-latest
      steps:
        - name: 'Checkout Code'
          uses: actions/checkout@v4
  
        - name: 'Print Current Workspace'
          run: |
            echo "Current Workspace: ${{ inputs.workspace }}"
  
  
    deploy_project:
        needs: infra 
        environment: ${{ inputs.workspace }}
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout Code'
              uses: actions/checkout@v4
            - name: 'Current workspace for deploy'
              run: |
                echo "Current workspace for deploy: ${{ inputs.workspace }}"
                
            - name: Download Artifact
              uses: actions/download-artifact@v2
              with:
                name: my-artifact


    deploy_functions:
        needs: infra
        environment: ${{ inputs.workspace }}
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout Code'
              uses: actions/checkout@v4

            - name: 'Current workspace for deploy functions'
              run: |
                echo "Current workspace for deploy functions: ${{ inputs.workspace }}"
    

    